<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.1;net481</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>GameSharp.Sandbox.Java</RootNamespace>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net481'))" Include="System.IO.Compression" Version="4.3.0" />
    <ProjectReference Include="..\GameSharp.Sandbox.Host\GameSharp.Sandbox.Host.csproj" />
  </ItemGroup>

</Project>
