<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GameSharp.Sandbox</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
    <EnableStreamJsonRpcInterceptors>true</EnableStreamJsonRpcInterceptors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameSharp.Collections\GameSharp.Collections.csproj" />
    <ProjectReference Include="..\GameSharp.Sandbox\GameSharp.Sandbox.csproj" />
    <Using Include="GameSharp.Collections" />
    <Using Include="GameSharp.Collections.Immutable" />
    <Using Include="StreamJsonRpc" />
  </ItemGroup>

</Project>
