<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;netstandard2.1</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>   
    <RootNamespace>$(SolutionName).$(MSBuildProjectName)</RootNamespace>
    <AssemblyName>$(SolutionName).$(MSBuildProjectName)</AssemblyName>  
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\..\bin\$(Configuration)\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Collections\Collections.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <Compile Remove="**\*.netstandard2.1.cs" />
    <None Include="**\*.netstandard2.1.cs" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <Compile Remove="**\*.net9.0.cs" />
    <None Include="**\*.net9.0.cs" />
  </ItemGroup>

</Project>
