<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.1;net481</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>GameSharp.Sandbox.Dotnet</RootNamespace>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net10.0'">
    <PackageReference Include="System.Reflection.Metadata" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameSharp.Sandbox.Host\GameSharp.Sandbox.Host.csproj" />
  </ItemGroup>

</Project>
